server:
  port: 9006
spring:
  application:
    name: food-payment-service
  cloud:
    stream:
      bindings:
        output: deliveryorders
  datasource:
    url: jdbc:mysql://localhost:3306/paydb
    username: root
    password: dang
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    suffix: .html
    encoding: UTF-8
    cache: false