#rabbitmq:
#  image: rabbitmq:3.6.1-management
#  ports:
#    - "5672:5672"
#    - "15672:15672"
#mongodb:
#  image: mongo:3.4.4
#  ports:
#    - "27017:27017"
#mysql:
#  image: mysql:8
#  ports:
#    - "3306:3306"
#  environment:
#    MYSQL_ROOT_PASSWORD: "dang"
#    MYSQL_DATABASE: "food_info_db"
db:
  image: mysql:8
  ports:
    - "3306:3306"
  volumes:
    - ./db:/var/lib/mysql
  environment:
    - MYSQL_DATABASE=fooddb
    - MYSQL_ROOT_PASSWORD=dang