server:
  port: 9005
spring:
  application:
    name: food-order-service
  thymeleaf:
    suffix: .html
    encoding: UTF-8
    cache: false
com:
  dang:
    food:
      payment: http://localhost:9006

